import { expect, test, beforeAll } from "bun:test";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { locate } from "../../src/parse/document.js";
import { build } from "../../src/model/build.js";
import { check } from "../../src/eval/check.js";
import { fmt } from "../../src/write/fmt.js";
import { installStub } from "../support/stub-engine.js";

// the isolation proof: a third engine, registered by a test, drives the whole
// pipeline without a line changing in graph/check/fmt/staleness
beforeAll(() => installStub("stub"));

const TABLE = `| Item | Price | Qty |  Net |
|------|------:|----:|-----:|
| pen  |  5.00 |   2 | 10.00 |
| ink  |  3.00 |   4 | 12.00 |
`;

const SRC = `${TABLE}
\`\`\`vmark #order
Net = Price * Qty
chart cost as stub of Net labelled Item
\`\`\`

![cost](charts/cost.svg)<!--vmark=order.cost-->
`;

function scratch(src = SRC): string {
  const dir = mkdtempSync(join(tmpdir(), "vmark-art-"));
  const doc = join(dir, "doc.md");
  writeFileSync(doc, src);
  return doc;
}

const run = (doc: string) => check(build(locate(readFileSync(doc, "utf8"))), { docPath: doc });

test("a missing artifact is STALE, naming the file", () => {
  const doc = scratch();
  const r = run(doc);
  const f = r.findings.find((x) => x.code === "STALE");
  expect(f?.artifact).toBe("charts/cost.svg");
  expect(f?.message).toContain("artifact missing");
  expect(r.exitCode).toBe(1);
});

test("fmt writes the artifact, then check is clean and fmt is idempotent", () => {
  const doc = scratch();
  const r1 = fmt(readFileSync(doc, "utf8"), { docPath: doc });
  expect(r1.artifacts).toHaveLength(1);
  mkdirSync(join(doc, "..", "charts"), { recursive: true });
  writeFileSync(r1.artifacts[0]!.target, r1.artifacts[0]!.svg);

  expect(run(doc).findings.filter((f) => f.code === "STALE")).toHaveLength(0);
  expect(run(doc).exitCode).toBe(0);

  const r2 = fmt(readFileSync(doc, "utf8"), { docPath: doc });
  expect(r2.artifacts).toHaveLength(0);
});

test("a byte-different artifact is STALE", () => {
  const doc = scratch();
  const r1 = fmt(readFileSync(doc, "utf8"), { docPath: doc });
  const target = r1.artifacts[0]!.target;
  mkdirSync(join(doc, "..", "charts"), { recursive: true });
  writeFileSync(target, r1.artifacts[0]!.svg.replace("</svg>", "<!--x--></svg>"));
  const f = run(doc).findings.find((x) => x.code === "STALE");
  expect(f?.message).toContain("out of date");
});

test("CRLF on disk does not make an artifact look stale", () => {
  const doc = scratch();
  const r1 = fmt(readFileSync(doc, "utf8"), { docPath: doc });
  mkdirSync(join(doc, "..", "charts"), { recursive: true });
  writeFileSync(r1.artifacts[0]!.target, r1.artifacts[0]!.svg.replace(/\n/g, "\r\n"));
  expect(run(doc).findings.filter((f) => f.code === "STALE")).toHaveLength(0);
});

test("a file that is not visimark's is never overwritten", () => {
  const doc = scratch();
  mkdirSync(join(doc, "..", "charts"), { recursive: true });
  writeFileSync(join(doc, "..", "charts", "cost.svg"), "<svg>hand drawn</svg>");
  const f = run(doc).findings.find((x) => x.code === "ARTIFACT");
  expect(f?.message).toContain("was not generated by visimark");
  expect(fmt(readFileSync(doc, "utf8"), { docPath: doc }).artifacts).toHaveLength(0);
});

test("two charts writing to one path is an ARTIFACT finding", () => {
  installStub("stub2");
  const src = `${TABLE}
\`\`\`vmark #order
Net = Price * Qty
chart cost as stub of Net labelled Item
chart other as stub2 of Net labelled Item
\`\`\`

![a](charts/cost.svg)<!--vmark=order.cost-->
![b](charts/cost.svg)<!--vmark=order.other-->
`;
  const doc = scratch(src);
  const f = run(doc).findings.find((x) => x.code === "ARTIFACT");
  expect(f?.message).toContain("two charts write to");
});

test("a chart with no image line is an ARTIFACT finding", () => {
  const doc = scratch(`${TABLE}
\`\`\`vmark #order
Net = Price * Qty
chart cost as stub of Net labelled Item
\`\`\`
`);
  const f = run(doc).findings.find((x) => x.code === "ARTIFACT");
  expect(f?.message).toContain("no image reference");
});

test("an unknown engine is an ARTIFACT finding with a suggestion", () => {
  const doc = scratch(SRC.replace("as stub of", "as stbu of"));
  const f = run(doc).findings.find((x) => x.code === "ARTIFACT");
  expect(f?.message).toContain("unknown chart type");
  expect(f?.suggestion).toBe("stub");
});

test("a path escaping the document's directory is refused", () => {
  const doc = scratch(SRC.replace("charts/cost.svg", "../escape.svg"));
  const f = run(doc).findings.find((x) => x.code === "ARTIFACT");
  expect(f?.message).toContain("escapes the document's directory");
});

test("a non-numeric series is an ARTIFACT finding", () => {
  const doc = scratch(SRC.replace("of Net labelled Item", "of Item labelled Item"));
  const f = run(doc).findings.find((x) => x.code === "ARTIFACT");
  expect(f?.message).toContain("needs numbers");
});

test("the chart result is reported for explain / --json", () => {
  const doc = scratch();
  const c = run(doc).charts[0]!;
  expect(c).toMatchObject({
    sheetId: "order",
    name: "cost",
    engine: "stub",
    series: ["Net"],
    labels: "Item",
    path: "charts/cost.svg",
    state: "missing",
  });
});
