import { beforeAll, describe, expect, test } from "bun:test";
import { onDisk } from "../../src/fs/node-reader.js";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeArtifact } from "../../src/artifact/write.js";
import { fmt } from "../../src/write/fmt.js";
import { installStub } from "../support/stub-engine.js";

/**
 * The only tests in the repo that stand in for a concurrent attacker.
 *
 * Each one takes the real verdict `fmt` produced, then mutates the target
 * *before* calling `writeArtifact` - which is exactly the window the CLI
 * leaves open between `eval/check-charts.ts` settling a chart and
 * `cli/commands.ts` writing it. Nothing here is reachable from a document
 * alone; it needs another process with write access to the directory.
 */

beforeAll(() => installStub("stub"));

const SRC = `| Item | Price | Qty |   Net |
|------|------:|----:|------:|
| pen  |  5.00 |   2 | 10.00 |

\`\`\`vmark #order
Net = Price * Qty
chart cost as stub of Net labelled Item
\`\`\`

![cost](charts/cost.svg)<!--vmark=order.cost-->
`;

/** a document, its verdict, and the artifact directory ready to be written */
function staged(): { dir: string; doc: string; write: ReturnType<typeof plan> } {
  const dir = mkdtempSync(join(tmpdir(), "vmark-toctou-"));
  const doc = join(dir, "doc.md");
  writeFileSync(doc, SRC);
  mkdirSync(join(dir, "charts"), { recursive: true });
  return { dir, doc, write: plan(doc) };
}

function plan(doc: string) {
  const r = fmt(readFileSync(doc, "utf8"), { doc: onDisk(doc) });
  expect(r.artifacts).toHaveLength(1);
  return r.artifacts[0]!;
}

test("the happy path still writes, and the verdict is `missing` first", () => {
  const { write } = staged();
  expect(write.state).toBe("missing");
  expect(writeArtifact(write)).toEqual({ ok: true });
  expect(readFileSync(write.target, "utf8")).toBe(write.svg);
});

// finding 2 of the plan: the marker rule is what protects a person's own
// file, and it was decided at check time and used much later
test("a file planted after a `missing` verdict is not overwritten", () => {
  const { write } = staged();
  writeFileSync(write.target, "a human drew this");
  expect(writeArtifact(write)).toEqual({
    err: "`" + write.target + "` changed between the check and the write",
  });
  expect(readFileSync(write.target, "utf8")).toBe("a human drew this");
});

test("an unmarked file swapped in after a `stale` verdict is not overwritten", () => {
  const { doc, write } = staged();
  expect(writeArtifact(write)).toEqual({ ok: true });

  writeFileSync(write.target, write.svg.replace("</svg>", "<!--drift--></svg>"));
  const stale = plan(doc);
  expect(stale.state).toBe("stale");

  // the swap: same path, no longer ours
  writeFileSync(stale.target, "a human drew this");
  expect(writeArtifact(stale)).toEqual({
    err: "`charts/cost.svg` exists and was not generated by visimark",
  });
  expect(readFileSync(stale.target, "utf8")).toBe("a human drew this");
});

test("a foreign artifact swapped in after a `stale` verdict is not overwritten", () => {
  const { doc, write } = staged();
  expect(writeArtifact(write)).toEqual({ ok: true });
  writeFileSync(write.target, write.svg.replace("</svg>", "<!--drift--></svg>"));
  const stale = plan(doc);

  writeFileSync(stale.target, '<metadata><visimark sheet="other" chart="thing"/></metadata>');
  expect(writeArtifact(stale)).toEqual({
    err: "`charts/cost.svg` belongs to chart `other.thing`",
  });
});

describe.skipIf(process.platform === "win32")("symlink planted after the verdict", () => {
  test("a `missing` target swapped for a symlink out of the tree is refused", () => {
    const { dir, write } = staged();
    const victim = join(dir, "..", "vmark-toctou-victim.txt");
    writeFileSync(victim, "SECRET");
    symlinkSync(victim, write.target);

    expect(writeArtifact(write)).toEqual({
      err: "`" + write.target + "` changed between the check and the write",
    });
    expect(readFileSync(victim, "utf8")).toBe("SECRET");
    rmSync(victim);
  });

  test("a `stale` target swapped for a symlink out of the tree is refused", () => {
    const { dir, doc, write } = staged();
    expect(writeArtifact(write)).toEqual({ ok: true });
    writeFileSync(write.target, write.svg.replace("</svg>", "<!--drift--></svg>"));
    const stale = plan(doc);

    const victim = join(dir, "..", "vmark-toctou-victim2.txt");
    writeFileSync(victim, "SECRET");
    rmSync(stale.target);
    symlinkSync(victim, stale.target);

    expect(writeArtifact(stale)).toEqual({
      err: "`" + stale.target + "` changed between the check and the write",
    });
    expect(readFileSync(victim, "utf8")).toBe("SECRET");
    rmSync(victim);
  });
});
