import { closeSync, fstatSync, ftruncateSync, readFileSync, writeSync } from "node:fs";
import { openForWrite } from "../fs/open.js";
import type { ArtifactWrite } from "../write/fmt.js";
import { readMarker } from "./stale.js";

/**
 * Writing a generated artifact, with the gate's verdict re-proved against the
 * descriptor being written through.
 *
 * `check` decided long ago that this target was `missing` or was a `stale`
 * artifact of ours. Two rules rest on that decision - containment in the
 * document's directory, and the refusal to overwrite any file lacking
 * VisiMark's marker, which is what protects a hand-drawn SVG. Both were
 * settled against a *name*, and the write happens after the rest of the run.
 *
 * So both are re-established here against the open file itself: `O_EXCL` for
 * a target that was supposed to be absent, and for one that was supposed to
 * be ours, the marker read back out of the same descriptor the bytes then go
 * into. The limits of that are on `fs/open.ts`.
 */
export function writeArtifact(a: ArtifactWrite): { ok: true } | { err: string } {
  const opened = openForWrite(a.target, a.state === "stale");
  if ("err" in opened) return { err: opened.err };
  const fd = opened.ok;
  try {
    if (a.state === "stale") {
      const refusal = confirmOwnership(fd, a);
      if (refusal) return { err: refusal };
    }
    ftruncateSync(fd, 0);
    writeSync(fd, a.svg, 0, "utf8");
    return { ok: true };
  } catch (e) {
    const code = (e as NodeJS.ErrnoException | undefined)?.code;
    return { err: "`" + a.target + "` could not be written" + (code ? " (" + code + ")" : "") };
  } finally {
    closeSync(fd);
  }
}

/**
 * The `unowned` / `foreign` refusals of `eval/check-charts.ts`, re-run on the
 * descriptor. The wording deliberately matches the findings that command
 * produces, so the same situation reads the same way whether it is caught at
 * check time or at write time.
 */
function confirmOwnership(fd: number, a: ArtifactWrite): string | null {
  const named = "`" + (a.path ?? a.target) + "`";
  // a symlink cannot reach here (O_NOFOLLOW), but a fifo or a device can be
  // opened read-write, and neither is a file we ever generated
  if (!fstatSync(fd).isFile()) return named + " is not a regular file";

  const mark = readMarker(readFileSync(fd, "utf8"));
  if (!mark) return named + " exists and was not generated by visimark";
  if (mark.sheet !== a.sheetId || mark.chart !== a.chart) {
    return named + " belongs to chart `" + mark.sheet + "." + mark.chart + "`";
  }
  return null;
}
