/**
 * Renders the two generated function documents from `lang/reference.ts`.
 *
 * `docs/function-reference.md` is the whole file. The table in
 * `docs/visimark-design.md` section 4 is replaced between HTML-comment
 * markers; everything outside them — the shape prose, the exact-arity
 * paragraph, the `Σ` alias note — is hand-written and untouched.
 *
 * Run with `bun run gen:docs`. CI re-runs it and fails on a diff.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  describeFunction,
  functionNames,
  type FnEntry,
} from "../packages/visimark/src/lang/reference.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BEGIN = "<!-- generated: function-table — `bun run gen:docs` -->";
const END = "<!-- /generated: function-table -->";

const entries = (): FnEntry[] => functionNames().map((n) => describeFunction(n)!);
const sig = (e: FnEntry): string => `${e.name}(${e.params.map((p) => p.name).join(", ")})`;
const sentence = (s: string): string => `${s[0]!.toUpperCase()}${s.slice(1)}`;

/**
 * The `Meaning` cell: the summary, then each error rendered back into the
 * prose form the hand-written table used. This is why `FnError.when` must be a
 * noun phrase.
 */
const meaning = (e: FnEntry): string =>
  [e.summary, ...e.errors.map((x) => `${x.when} is a \`${x.code}\` error`)].join("; ");

export function renderTable(): string {
  const rows = entries().map(
    (e) => `| \`${sig(e)}\` | ${e.kind} | ${e.arity} | ${e.precisionRule} | ${meaning(e)} |`,
  );
  return [
    BEGIN,
    "",
    "| Function | Kind | Arity | Precision | Meaning |",
    "|----------|------|------:|-----------|---------|",
    ...rows,
    "",
    "Parameters, precision and worked examples for each are in",
    "[`function-reference.md`](function-reference.md), or `visimark ref NAME`.",
    "",
    END,
  ].join("\n");
}

function section(e: FnEntry): string {
  const lines: string[] = [];
  lines.push(`### \`${sig(e)}\``, "");
  lines.push(`${sentence(e.summary)}.`, "");
  lines.push(`**Shape:** ${e.kind}, ${e.arity} argument${e.arity === 1 ? "" : "s"}.`, "");
  lines.push("| Parameter | Type | Meaning |", "|---|---|---|");
  for (const p of e.params) lines.push(`| \`${p.name}\` | ${p.type} | ${p.note} |`);
  lines.push("", `**Returns:** ${e.returns}.`, "");
  if (e.precision) lines.push(`**Precision:** ${e.precision}`, "");
  if (e.errors.length > 0) {
    lines.push("**Errors**", "");
    for (const x of e.errors) lines.push(`- ${sentence(x.when)} — \`${x.code}\``);
    lines.push("");
  }
  // A table, not a ```vmark fence: these are expressions, not bindings, so a
  // vmark fence would be source `visimark check` could not read.
  lines.push("**Examples**", "");
  lines.push("| Expression | Is |", "|---|---|");
  for (const x of e.examples) lines.push(`| \`${x.expr}\` | \`${x.is}\` |`);
  lines.push("");
  if (e.see && e.see.length > 0) {
    lines.push(`**See also:** ${e.see.map((s) => `\`${s}\``).join(", ")}`, "");
  }
  return lines.join("\n");
}

export function renderReference(): string {
  const all = entries();
  return (
    [
      "# VisiMark function reference",
      "",
      "**Generated from `packages/visimark/src/lang/reference.ts` by",
      "`bun run gen:docs`. Do not edit this file by hand — edit the registry.**",
      "",
      "Every example below is executed against the evaluator in CI",
      "(`packages/visimark/test/lang/reference-examples.test.ts`), so an example",
      "that stops being true fails the build.",
      "",
      "The narrative account of the language is",
      "[`visimark-design.md`](visimark-design.md); why each function exists is in",
      "[`vocab/`](vocab/). This file answers only what each one does.",
      "",
      "A reduce example is shown against a three-row table `t` whose `Amount`",
      "column holds `10.00`, `20.00` and `30.00`.",
      "",
      "## Reduces",
      "",
      "A reduce is column → scalar and takes a bare column reference, never an",
      "expression.",
      "",
      ...all.filter((e) => e.kind === "reduce").map(section),
      "## Maps",
      "",
      "A map is scalar → scalar and runs once per row inside a column rule.",
      "",
      ...all.filter((e) => e.kind === "map").map(section),
      // Tables, and nothing in them to derive: the marker is what says so, and
      // keeps the file clean under `visimark check` like the other prose docs.
      "<!--vmark:no-formulas-->",
    ]
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  );
}

function main(): void {
  writeFileSync(join(ROOT, "docs/function-reference.md"), renderReference());
  const path = join(ROOT, "docs/visimark-design.md");
  const design = readFileSync(path, "utf8");
  const a = design.indexOf(BEGIN);
  const b = design.indexOf(END);
  if (a === -1 || b === -1) {
    throw new Error("function-table markers not found in docs/visimark-design.md");
  }
  writeFileSync(path, design.slice(0, a) + renderTable() + design.slice(b + END.length));
}

if (process.argv[1]?.endsWith("gen-function-reference.ts")) main();
