/**
 * Renders `editors/obsidian/src/templates.ts` from the Markdown files in
 * `editors/obsidian/templates/`. Run with `bun run gen:obsidian-templates`;
 * `editors/obsidian/test/templates.test.ts` re-runs it in memory and fails on
 * a diff, the way `gen-function-reference.ts` and `gen-mcp-skill.ts` are
 * treated by their CI jobs.
 *
 * **Why the templates are `.md` files and not string literals in TypeScript.**
 * A template's whole contract is that it passes `visimark check` with zero
 * findings before anything is edited (v1 row 10, manual test §2.10). A `.md`
 * file can be handed to the CLI, to `fmt`, to a Markdown renderer and to a
 * reviewer's eye; a template literal can be handed to none of those, and the
 * first person to fix a number inside one by hand would have no way to know
 * whether they had got it right.
 *
 * **Why it is generated rather than imported.** The plugin ships one `main.js`
 * and nothing beside it, so the text has to be *in* the bundle. esbuild would
 * do that with a `.md` text loader — but `tsc` and `bun test` would each need
 * their own arrangement to agree, and this package already has one three-way
 * resolution problem solved by hand (`tsconfig.json`'s `paths`). Generating a
 * `.ts` file means every resolver reads plain TypeScript and there is nothing
 * to keep in agreement except this script, which a test runs.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "editors", "obsidian", "templates");
const out = join(root, "editors", "obsidian", "src", "templates.ts");

/** `invoice.md` → `invoice`, and the order the command palette shows them in */
export const TEMPLATE_ORDER = ["invoice", "budget", "capacity", "experiment"] as const;

/** The title each one gets in the palette. Sentence case — Obsidian's rule. */
const TITLES: Record<string, string> = {
  invoice: "Invoice",
  budget: "Monthly budget",
  capacity: "Team capacity",
  experiment: "Experiment log",
};

export function render(read: (name: string) => string): string {
  const names = TEMPLATE_ORDER;
  const entries = names.map((name) => {
    // A template is Markdown and contains backticks, `${` and backslashes.
    // JSON.stringify is the only escaping that is certainly right for all
    // three, and it round-trips exactly — which is what the freshness test
    // compares.
    const body = JSON.stringify(read(name));
    return `  {\n    id: ${JSON.stringify(name)},\n    title: ${JSON.stringify(
      TITLES[name],
    )},\n    body: ${body},\n  },`;
  });
  return `// Generated by scripts/gen-obsidian-templates.ts from
// editors/obsidian/templates/*.md. Do not edit by hand: edit the Markdown,
// which the CLI can check, and run \`bun run gen:obsidian-templates\`.
// editors/obsidian/test/templates.test.ts fails on a diff.

export interface Template {
  /** the file's basename, and the suffix of the command id */
  readonly id: string;
  /** what the command palette shows, in sentence case */
  readonly title: string;
  /** the document, verbatim */
  readonly body: string;
}

export const TEMPLATES: readonly Template[] = [
${entries.join("\n")}
];
`;
}

function readTemplate(name: string): string {
  return readFileSync(join(dir, `${name}.md`), "utf8");
}

export function sourceNames(): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.replace(/\.md$/, ""))
    .sort();
}

if (import.meta.main) {
  const declared = [...TEMPLATE_ORDER].sort();
  const found = sourceNames();
  if (declared.join(",") !== found.join(",")) {
    console.error(
      `templates/ holds ${found.join(", ")} but TEMPLATE_ORDER names ${declared.join(", ")}. ` +
        `A template with no place in the order has no command; add it above.`,
    );
    process.exit(1);
  }
  writeFileSync(out, render(readTemplate));
  console.log(`wrote ${out} from ${found.length} templates`);
}
