/**
 * The pure half of `gen-articles.ts`: no filesystem access, so it is unit-
 * tested directly. Markdown rendering reuses the repo's existing
 * remark-parse/remark-gfm parse pipeline (see
 * packages/visimark/src/parse/document.ts) with the render-to-HTML half
 * (remark-rehype, rehype-stringify) added on top — one Markdown dialect
 * across the whole repo, not a second one introduced for this page.
 */
import rehypeStringify from "rehype-stringify";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { unified } from "unified";
import {
  articleBody,
  articlePublishedUrl,
  articleSourceUrl,
  type Article,
} from "../packages/visimark/src/site/articles.js";
import { escapeHtml } from "../packages/visimark/src/site/dom.js";

const SITE_DESCRIPTION =
  "Articles about VisiMark: keeping the numbers in Markdown checked, on every commit.";
const SITE_URL = "https://michal-niedzwiedzki.github.io/visimark/";

export function renderMarkdown(markdown: string): string {
  return String(
    unified()
      .use(remarkParse)
      .use(remarkGfm)
      .use(remarkRehype)
      .use(rehypeStringify)
      .processSync(markdown),
  );
}

/** The following entry in `articles.json` file order, wrapping from the last
 *  entry back to the first. */
export function nextArticle(articles: Article[], index: number): Article {
  return articles[(index + 1) % articles.length]!;
}

/** A small, deterministic string hash (FNV-1a), used only to break a tie
 *  reproducibly — never `Math.random()`, so re-running the generator with no
 *  data change produces byte-identical output. */
function hashString(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** The article sharing the most tags with `articles[index]`, excluding that
 *  article itself and `next` (so the two "More to read" columns are never
 *  the same article). Ties are broken by a hash of the current article's
 *  slug. `undefined` when no other candidate exists. */
export function relatedArticle(
  articles: Article[],
  index: number,
  next: Article,
): Article | undefined {
  const self = articles[index]!;
  const candidates = articles.filter((a) => a.slug !== self.slug && a.slug !== next.slug);
  if (candidates.length === 0) return undefined;
  const sharedTags = (a: Article): number => a.tags.filter((t) => self.tags.includes(t)).length;
  const maxShared = Math.max(...candidates.map(sharedTags));
  const tied = candidates.filter((a) => sharedTags(a) === maxShared);
  return tied[hashString(self.slug) % tied.length]!;
}

function pageShell(opts: {
  base: string;
  title: string;
  ogTitle: string;
  ogUrl: string;
  body: string;
}): string {
  const { base, title, ogTitle, ogUrl, body } = opts;
  const home = base === "" ? "./" : base;
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <!--
      Generated by \`bun run gen:articles\` from docs/articles/articles.json —
      do not hand-edit. A <meta> policy, because GitHub Pages cannot send
      headers. The page has no script of its own, so there is nothing to
      grant beyond style and same-origin images.
    -->
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'none';
               style-src 'self';
               img-src 'self';
               base-uri 'none';
               form-action 'none'"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="${SITE_DESCRIPTION}" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="VisiMark" />
    <meta property="og:title" content="${escapeHtml(ogTitle)}" />
    <meta property="og:description" content="${SITE_DESCRIPTION}" />
    <meta property="og:url" content="${escapeHtml(ogUrl)}" />
    <meta property="og:image" content="${SITE_URL}og-card.png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="VisiMark" />
    <meta name="twitter:card" content="summary_large_image" />
    <title>${escapeHtml(title)}</title>
    <link rel="icon" type="image/webp" href="${base}assets/visimark.webp" />
    <link rel="stylesheet" href="${base}styles.css" />
  </head>
  <body>
    <div class="wrap">
      <header class="masthead">
        <a href="${home}"><img src="${base}assets/visimark.webp" alt="VisiMark logo" /></a>
        <h1>Articles</h1>
        <p class="subtitle">on the numbers in your Markdown</p>
      </header>
    </div>

    <p class="install-cta">
      <a href="${home}">Home</a>
      <a href="${base}playground.html">Try in Playground</a>
      <a href="${base}tutorial.html">Read the tutorial</a>
      <a href="${base}ci.html">Continuous integration</a>
      <a href="${base}articles.html">Articles</a>
    </p>

    <div class="wrap wrap-rest">
${body}
    </div>
  </body>
</html>
`;
}

export function renderArticlesListPage(articles: Article[]): string {
  const cards = articles
    .map((a) => `        <article class="article-card">${articleBody(a, "h2")}</article>`)
    .join("\n");
  return pageShell({
    base: "",
    title: "VisiMark articles",
    ogTitle: "VisiMark articles",
    ogUrl: `${SITE_URL}articles.html`,
    body: `      <main class="articles-list">
${cards}
      </main>`,
  });
}

function readerHeader(a: Article): string {
  const published = articlePublishedUrl(a);
  return `<header class="reader-head">
            <h1>${escapeHtml(a.title)}</h1>
            <p class="reader-meta">By ${escapeHtml(a.author)} &middot; ${a.tags.map(escapeHtml).join(", ")}</p>
            <p class="reader-links">${
              published ? `<a href="${escapeHtml(published)}">Also published here</a> &middot; ` : ""
            }<a href="${escapeHtml(articleSourceUrl(a))}">Markdown source</a> &middot; <a href="../../articles.html">All articles</a></p>
          </header>`;
}

function moreToRead(next: Article, related: Article | undefined): string {
  const cards = [next, related]
    .filter((a): a is Article => a !== undefined)
    .map((a) => `          <article class="article-card">${articleBody(a, "h3", "../../")}</article>`)
    .join("\n");
  return `        <div class="reader-more">
          <h2>More to read</h2>
          <div class="reader-more-grid">
${cards}
          </div>
        </div>`;
}

export function renderArticlePage(
  article: Article,
  bodyHtml: string,
  next: Article,
  related: Article | undefined,
): string {
  return pageShell({
    base: "../../",
    title: `${article.title} — VisiMark`,
    ogTitle: article.title,
    ogUrl: `${SITE_URL}articles/${article.slug}/`,
    body: `      <main class="reader">
        <div class="reader-inner">
          ${readerHeader(article)}
          <div class="reader-body">${bodyHtml}</div>
        </div>
${moreToRead(next, related)}
      </main>`,
  });
}
